name: CI

on:
  push:
  pull_request:

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rokit
        uses: paradoxum-games/setup-rokit@v3
        with:
          cache: true

      - name: Check formatting
        run: stylua --check .
